### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by jaanos** [nikolajcandellari/APPR-2017-18#1]
Trenutno imaš uvoz narejen tako:

https://github.com/nikolajcandellari/APPR-2017-18/blob/17501a43d64abf180ed6abf435a1cdb80f7bdbca/uvoz/osnovna%20tabela.R#L3-L6

Ker si pri uvažanju navedel absolutno pot, si si zagotovil, da bo program deloval samo in izključno na tvojem računalniku. Če imaš v RStudiu odprt projekt (če zgoraj desno piše *Project: (None)*, potem klikni tja, izberi *Open Project...* in poišči datoteko `APPR-2017-18.Rproj` v tvoji kopiji repozitorija), potem je trenutni delovni imenik glavni imenik projekta in lahko poti do datotek navajaš relativno na ta imenik. Svetoval bi tudi, da se izogibaš uporabi presledkov (pa tudi šumnikov in drugih posebnih znakov) v imenih datotek (tako podatkov kot programov), saj znajo povzročati probleme.

Poleg tega namesto `read.csv` (s piko) raje uporabi funkcijo `read_csv` (s podčrtajem) iz knjižnice `readr`. Kolikor vidim, želiš podatke samo za gasilska društva. Ker so imena stolpcev v šesti vrstici, raje izpusti samo prvih 5 vrstic, nato pa s funkcijo `filter` iz knjižnice `dplyr` pobereš ven samo želene podatke:
```R
stevilo_intervencij <- read_csv("podatki/Pregled stevila intervencij.csv", skip = 5) %>%
  filter(Vrsta == "Prostovoljna teritorialna gasilska društva") %>% select(-Vrsta)
```
Funkcija `select` se uporablja za izbiro stolpcev - v tem primeru izpusti stolpec `Vrsta`, saj ima po filtriranju povsod enako vrednost in je zato nepotreben.

Da naložiš potrebne knjižnice, bo najlažje, če pred začetkom dela poženeš program `lib/libraries.r` - tja lahko dodajaš tudi uvažanje morebitnih ostalih knjižnic, ki jih boš morda še potreboval. Pri prevajanju poročila se bo najprej zagnal ta program, tako da bodo kasneje na voljo vse knjižnice.

Še to: ukaza `View` ne vključuj v svoj program. Zaenkrat ga sicer lahko še pustiš tam, da vidiš uvožene podatke, kasneje ga pa odstrani, da se razpredelnica ne bo odpirala med prevajanjem poročila.

**Comment by nikolajcandellari** [comment]
Najlepsa hvala. Bom popravil.
