### ISSUE TITLE
Uvazanje podatkov s spletne strani SPIN

### ISSUE THREAD

**Issue by nikolajcandellari** [nikolajcandellari/APPR-2017-18#2]
Kot sem vam ze vceraj razlozil se sam zal ne znajdem na tej spletni strani ter ne znam iz njem pridobiti podatkov... rad bi torej pridobil podatke o kategoriji intervencij in stevilu teh intervencij za vsako drustvo ter te podatke vstavil v mojo osnovno tabelo ki sem jo ze uredil v rstudiu.
Link: http://spin.sos112.si/SPIN2/Javno/Porocila/

**Comment by jaanos** [comment]
Sem se kar malo namatral, da sem uspel dobit te podatke. Tukaj je sedaj delujoča koda:

https://gist.github.com/jaanos/587aec52822273d9c3b852b1c2937ddc

Za delovanje je potrebna knjižnica `httr` - najbolje, da jo uvoziš kar v `lib/libraries.r`. Za uvoz vseh podatkov pokličeš funkcijo `get.reports()` - ta vrne razpredelnico s stolpci `aktivnost`, `stevilo` in `enota`.

Pobiranje čisto vseh podatkov bo najbrž dolgo trajalo - s parametrom `unit.ids` lahko tako določiš, za katere enote hočeš pobrati podatke (npr. `get.reports(unit.ids = 1:10)` ti pobere podatke za prvih 10 enot). Poleg tega lahko spreminjaš tudi tip enote (parameter `type` - privzeta vrednost 18 je za *Prostovoljna teritorialna gasilska društva*) in leto (parameter `year`). Naj opozorim, da sem opazil, da se vrstni red enot včasih spremeni - tako je včasih prvi *AJDOVEC*, drugič pa *ADLEŠIČI*.

Glede na to, da bo pobiranje podatkov dolgotrajno, svetujem, da si končno razpredelnico spraviš v obliko CSV (poglej si funkcijo `write.csv`). Tako v glavnem programu ne bo potrebno vsakič znova podatkov pridobivati s spletne strani, pač pa jih boš samo prebral z `read_csv`.

Bom še malo pokomentiral kodo z zgornje povezave, da bo bolj jasno, kaj se dogaja.

**Comment by nikolajcandellari** [comment]
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback 

ko poženem kodo mi tole napise...

**Comment by jaanos** [comment]
Ta napaka se navadno pojavi ob težavah z internetno povezavo. Poskusi ponovno - morda lahko poskusiš z manjšim številom enot (npr. `get.reports(unit.ids = 1:5)`).
