### ISSUE TITLE
analiza podatkov

### ISSUE THREAD

**Issue by nikolajcandellari** [nikolajcandellari/APPR-2017-18#4]
v kodi analize sem poizkusal left_join-ati dve tabeli in mankajoče podatke pridobiti iz druge join-ane tabele. pri tem sem si pomagal z for zanko vendar mi na koncu vrne vektor v katerem so namesto imena obcin stevila, ki si jih ne znam razložiti... vidite morda vi kaksno napake v kodi?

**Comment by jaanos** [comment]
Najprej, v `drustva po obcinah.R` ti manjka en zavit zaklepaj - verjetno pri prvi zanki `for`.

Števila se ti pojavljajo, ker imaš za stolpce faktorje, medtem ko ti `vector` naredi logični vektor, ki se z dodajanjem vrednosti nadgradi v številskega. Če prav razumem, želiš dobiti občino za vsako društvo, pri čemer najprej poizkusiš združiti po stolpcu `naslov`, če pa tako ne najdeš občine, jo poskusiš najti glede na stolpec `obcina`. Tako razpredelnico bi načeloma lahko dobil z uporabo funkcije `ifelse`:
```R
data_frame(drustvo = po.naslovih$drustvo,
           obcina = ifelse(is.na(po.postah$OBCINA),
                           po.naslovih$OBCINA, po.postah$OBCINA))
```
Vendar se problem pojavi, ker se kar 433 imen krajev pojavi večkrat (večinoma dvakrat, nekatera pa celo do sedemkrat). Tako že razpredelnici `po.naslovih` in `po.postah` nimata enakega števila vrstic (to je še en razlog, zakaj ni pametno uporabljati zanke `for`, saj se nam lahko take stvari hitro izmuznejo).

Poleg tega očitno tudi z uvozom občin za kraje ni vse v redu, saj imaš kar 702 različni občini - nekatere imajo sicer predpono *OBČINA* ali *MESTNA OBČINA*, zaradi česar se nekatere podvajajo, a vseeno so v seznamu tudi kraji, ki sami niso občine. Kot vidim, je npr. tabela krajev na [A](https://sl.wikipedia.org/wiki/Seznam_naselij_v_Sloveniji_(A)) napačno označena - imena občin so v drugem stolpcu. Glede na to, da imaš za vsako društvo ime pošte, lahko raje iz uvoženih krajev narediš seznam občin za vsako pošto (tukaj se imena ne ponavljajo, vsaj čez različne občine ne) in potem po tem združuješ.

**Comment by nikolajcandellari** [comment]
Oprostite, vendar mislim da zadnjega dela nisem razumel... 
Se pravi da bi ime pošte, gledal kot ime naselja ter gledal v kateri občini je?

**Comment by jaanos** [comment]
Če si pogledaš na [stran na Wikipediji z naselji na A](https://sl.wikipedia.org/wiki/Seznam_naselij_v_Sloveniji_(A)), si lahko opazil, da so bili stolpci zaporedoma označeni kot **Ime naselja**, **Poštna številka**, **Pošta** in **Občina**, kar pa je očitno napačno, saj so v drugem stolpcu imena občin, ne poštne številke. Ker pa v svojem uvozu za občine vzameš četrti stolpec, so uvoženi podatki napačni. Sem zdaj popravil na Wikipediji, da ne bo nadaljnje zmede.

Ker se pa imena naselij ponavljajo, bo bolje, da namesto po imenu naselja iščeš po pošti - združuješ torej po stolpcu `posta` iz razpredelnice `drustva.po.naslovih.in.postah`. Seveda bo potrebno namesto imen naselij uvoziti pošte, npr.
```R
library(rvest)
library(dplyr)
library(tidyr)
library(readr)

uvozi.poste <- function(crka) {
  link <- sprintf("https://sl.wikipedia.org/wiki/Seznam_naselij_v_Sloveniji_(%s)", crka)
  stran <- html_session(link) %>% read_html()
  tabela <- stran %>% html_nodes(xpath = "//table[contains(@class, 'wikitable')]") %>% .[[1]] %>%
    html_table(fill = TRUE)
  `Pošta` <- NA # če nimamo stolpca `Pošta`, bomo uporabili NA
  tabela %>% transmute(posta = parse_character(`Pošta`),
                       obcina = gsub("^(O|Mestna o)bčina ", "", `Občina`)) %>% drop_na(1)
}

abeceda <- "ABCČDEFGHIJKLMNOPRSŠTUVZŽ"
poste <- bind_rows(lapply(1:25, . %>% { uvozi.poste(substr(abeceda, ., .)) })) %>%
  arrange(posta) %>% unique()
```
Opažam sicer, da je v uvoženih podatkih kar nekaj napak ali zastarelih podatkov, ki pa jih lahko morda popraviš kar na Wikipediji. Še bolje bo, če združevanje opraviš po poštnih številkah, saj tako ne bo problemov z različnimi črkovanji imen pošt (okrajšave, dvojezična imena). Še vseeno pa se zna zgoditi, da bo kakšna pošta manjkala.
