### ISSUE TITLE
uvoz.naselji.po.obcinah.r

### ISSUE THREAD

**Issue by nikolajcandellari** [nikolajcandellari/APPR-2017-18#5]
na koncu te datoteke želim združiti vse manjše tabele v eno večjo(z uporabo bind.rows ) pri tem mi sistem vrne:
`In bind_rows_(x, .id) : Unequal factor levels: coercing to character`
kako bi to lahko popravil ? Je kakšna druga funkcija bolj primerna?

**Comment by jaanos** [comment]
Gre samo za to, da imaš v obstoječih razpredelnicah faktorje, ki pa imajo različne vrednosti. To opozorilo pove samo, da je bil združeni stolpec pretvorjen v znakovni vektor, tako da ni treba nič spreminjati, če sicer deluje.
