### ISSUE TITLE
geom_point()

### ISSUE THREAD

**Issue by nikolajcandellari** [nikolajcandellari/APPR-2017-18#6]
dober dan!
pri risanju grafa slovenskih občin sem za vizualizacijo vzel funkcijo 'geom_point()', ki stvar zelo lepo izriše, žal pa ta funkcija nima možnosti uporabe funkcije: 'fill=' kar bi moj graf naredilo veliko bolj pregleden.
Poizkušal sem graf izrisati tudi z nekaterimi drugimi funkcijami iz družine geom_* vendar se potem graf ne izriše pravilno...
imate morda kakšno idejo?

pa še primer kode:
`
ggplot(zemljevid, aes(long, lat, fill=OB_ID)) +  #zemljevid je tabela podatkov in OB_ID je ena od vrstic tu
          theme_bw() + 
          geom_point()
`

**Comment by jaanos** [comment]
Če prav razumem, želiš pobarvati točke? V ta namen namesto `fill` uporabi `color`.

**Comment by jaanos** [comment]
Če pa želiš risati zemljevid, uporabi `geom_polygon`, npr.
```R
ggplot() + geom_polygon(data = zemljevid, aes(x = long, y = lat,
                                              group = group, fill = OB_ID)) + theme_bw()
```
