### ISSUE TITLE
poklicne gasilske enote

### ISSUE THREAD

**Issue by nikolajcandellari** [nikolajcandellari/APPR-2017-18#7]
Med obdelovanjem podatkov iz tabele "vrste intervencij po drustvih.csv" , pobrane na internetni strani http://spin.sos112.si/spin2/javno/
sem opazil da funkcija, ki uvaža te podatke uvozi le podatke za prostovoljna društva ne pa tudi za poklicne enote. to sem želel narediti sam z isto funkcijo le da sem spremenil tip enot(za prostovoljna drustva je to 18, za poklicne enote pa 16) vendar mi v nadaljevanju funkcija vrne napako in sicer v while zanki:
`Error in while (nchar(out) < l) { : argument is of length zero`

**Comment by nikolajcandellari** [comment]
naletel sem še na eno težavo ki je nisem razumel. Ko sem iz internetne strani uvozil tabelo za poklicne enote so imena teh enot imela različne predpone (npr. "GARS JESENICE") zato sem se jih želel s pomočjo funkcije gsub("GARS ", "", enota) znebiti vendar se pri zagonu te funkcije stolpec ne spremeni kot sem si želel, poizkusil sem tudi strsplit("GARS JESENICE", " ") vedar tudi to ne deluje...

**Comment by jaanos** [comment]
Problem je v tem, da so namesto navadnih presledkov v nizih uporabljeni nedeljivi presledki. Svetujem, da jih najprej zamenjaš z navadnimi presledki, nato pa bi morale zamenjave delovati:
```R
nbsp <- rawToChar(as.raw(c(194, 160)))
poklicne$enota <- gsub(nbsp, " ", poklicne$enota)
poklicne$enota <- gsub("^GARS ", "", poklicne$enota)
```
